### ISSUE TITLE
有头视图时，图片不会适配，还是在中间位置

### ISSUE THREAD

**Issue by SunsgneDZ** [ZhipingYang/FORScrollViewEmptyAssistant#6]
RT

**Comment by ZhipingYang** [comment]
恩，占位图在cell为空的时候，都是居中的。这时候你可以设置 emptyCenterOffset 向下偏移量就是头部视图高度的一半

**Comment by SunsgneDZ** [comment]
[self.tableView emptyViewConfigerBlock:^(FOREmptyAssistantConfiger *configer) {
//        configer.emptyCenterOffset = CGPointMake(0, 200);
        configer.emptyImage = [UIImage imageNamed:@"empty_no_data"];
    }];
设置了不起作用啊

**Comment by ZhipingYang** [comment]
sorry 哈，这个方法被废弃了我一会就更新。

**Comment by SunsgneDZ** [comment]
thanks

**Comment by ZhipingYang** [comment]
已更新
